upstream frontend_catalog {
    server frontend-catalog:80;
}

upstream frontend_manager_system {
    server frontend-manager-system:81;
}

upstream backend_api {
    least_conn;
    server backend-api:8080;
}
